language: node_js
node_js:
  - "10.13.0"
dist: trusty
sudo: false

cache:
  directories:
    - node_modules

script:
  - npm run ci

deploy:
  provider: pages
  skip-cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  keep-history: true
  local-dir: dist/crypto-prices
  on:
    branch: master
